# Generated by Django 3.2.4 on 2021-06-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_number', models.CharField(max_length=64, unique=True)),
                ('swift_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(max_length=255)),
                ('internal_id', models.CharField(max_length=7)),
                ('team', models.CharField(choices=[('treasury', 'TREASURY'), ('non-treasury', 'NON-TREASURY')], max_length=255)),
                ('account', models.ManyToManyField(to='treasury_banking_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('create payment', 'CREATE PAYMENT'), ('approve payment', 'APPROVE PAYMENT'), ('safety administrator', 'SAFETY ADMINISTRATOR')], max_length=255)),
                ('aml_required', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to='treasury_banking_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255, unique=True)),
                ('bank', models.ManyToManyField(to='treasury_banking_app.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_banking_app.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_banking_app.company'),
        ),
    ]
