# Generated by Django 3.2.4 on 2021-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.CharField(choices=[('CR', 'Create Payment'), ('DP', 'Delete Payment'), ('AP', 'Approve Payment'), ('SA', 'Safety Administrator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('TRE', 'TREASURY'), ('NTRE', 'NON-TREASURY')], max_length=4),
        ),
    ]
