# Generated by Django 3.0.6 on 2021-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0003_auto_20210628_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='permission_type',
            field=models.CharField(choices=[('CR', 'Create Payment'), ('DP', 'Delete Payment'), ('AP', 'Approve Payment')], default='CR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
