# Generated by Django 3.0.6 on 2021-06-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0004_auto_20210628_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('CR', 'Create Payment'), ('DP', 'Delete Payment'), ('AP', 'Approve Payment')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission_type',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(to='treasury_banking_app.Permission'),
        ),
    ]
