# Generated by Django 3.0.6 on 2021-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0006_auto_20210630_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('CREATE_PAYMENT', 'Create Payment'), ('Delete Payment', 'Delete Payment'), ('APPROVE_PAYMENT', 'Approve Payment')], default='CREATE_PAYMENT', max_length=64),
        ),
    ]
