# Generated by Django 3.0.6 on 2021-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0009_administratorviewform_bankviewform_companyviewform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('CREATE_PAYMENT', 'Create Payment'), ('DELETE_PAYMENT', 'Delete Payment'), ('APPROVE_PAYMENT', 'Approve Payment')], max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(to='treasury_banking_app.Access'),
        ),
    ]
