# Generated by Django 3.0.6 on 2021-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0011_auto_20210702_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_type',
            field=models.CharField(max_length=64),
        ),
    ]
