# Generated by Django 3.2.4 on 2021-07-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0013_auto_20210703_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bank',
        ),
    ]
