# Generated by Django 3.2.4 on 2021-07-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0014_remove_company_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyCreateForm',
        ),
    ]
