# Generated by Django 3.2.4 on 2021-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0017_auto_20210710_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='login',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
