# Generated by Django 3.0.6 on 2021-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0021_auto_20210711_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('Austria', 'AT'), ('Belgium', 'BE'), ('Bulgaria', 'BG'), ('Switzerland', 'CH'), ('Czech Republic', 'CZ'), ('Germany', 'DE'), ('Denmark', 'DK'), ('Estonia', 'EE'), ('Spain', 'ES'), ('Finland', 'FI')], max_length=64),
        ),
    ]
