# Generated by Django 3.0.6 on 2021-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0022_auto_20210711_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password_repeat',
            field=models.CharField(max_length=20),
        ),
    ]
