# Generated by Django 3.0.6 on 2021-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0023_auto_20210711_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password_repeat',
            field=models.CharField(max_length=64),
        ),
    ]
