# Generated by Django 3.2.4 on 2021-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_banking_app', '0033_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='login',
            field=models.CharField(max_length=7),
        ),
    ]
